"""Public API for stateframe."""

from stateframe import save as save
from stateframe import files as files
from stateframe import sources as sources
from stateframe import workspace as workspace
from stateframe.api import (
    add_date_features,
    add_missing_indicators,
    add_ratio,
    apply_suggested_conversions,
    branch,
    clean_column_name,
    clean_column_names,
    clean_numeric_outliers,
    connect_web,
    impute_missing,
    is_save_mode,
    ledger_view,
    leaf,
    map_values,
    modeling_catalog,
    modeling_artifact,
    modeling_experiment,
    modeling_plan,
    one_hot_encode,
    optimize_footprint,
    plot,
    profile,
    pull,
    query,
    rename_columns,
    report,
    register_ipython_magics,
    scale_numeric,
    scan,
    scan_path,
    suggest_visuals,
    save_mode,
    tree_view,
    default_modeling_spec,
    unify_binary_flags,
    view,
    visual_artifact,
    visual_catalog,
    visualize,
    web,
    web_payload,
)
from stateframe.cleaning import CleaningPlan, TransformAction
from stateframe.branch import BranchRecorder
from stateframe.config import ScanConfig, SuggestedConfig
from stateframe.footprint import FootprintAction, FootprintPlan
from stateframe.help import help
from stateframe.help import help_getdata
from stateframe.help import help_tree
from stateframe.ledger import LedgerEntry, LedgerState, LensLedger
from stateframe.lens_registry import LensSpec, all_lenses, get_lens_spec
from stateframe.modeling import ModelingAction, ModelingExperimentResult, ModelingExperimentSpec, ModelingPlan
from stateframe.operations import OperationControl, OperationSpec, all_operation_specs, get_operation_spec
from stateframe.visualizer import VisualRecommendation
from stateframe.models import (
    BinaryProfile,
    ColumnProfile,
    DatasetSummary,
    EvidenceFact,
    Insight,
    Issue,
    LensResult,
    PlotResult,
    Profile,
    Recommendation,
    RecommendationList,
    ShapeHypothesis,
    TargetCandidate,
    TargetProfile,
    TaskInference,
    TimeCandidate,
    ValueProfile,
)
from stateframe.sources import (
    DataObject,
    DataSource,
    DataSourceError,
    FunctionDataSource,
    QueryResult,
)

__all__ = [
    "BinaryProfile",
    "BranchRecorder",
    "CleaningPlan",
    "ColumnProfile",
    "DatasetSummary",
    "DataObject",
    "DataSource",
    "DataSourceError",
    "EvidenceFact",
    "FootprintAction",
    "FootprintPlan",
    "FunctionDataSource",
    "Insight",
    "Issue",
    "LedgerEntry",
    "LedgerState",
    "LensResult",
    "LensLedger",
    "LensSpec",
    "OperationControl",
    "OperationSpec",
    "PlotResult",
    "Profile",
    "QueryResult",
    "Recommendation",
    "RecommendationList",
    "ModelingAction",
    "ModelingExperimentResult",
    "ModelingExperimentSpec",
    "ModelingPlan",
    "ScanConfig",
    "ShapeHypothesis",
    "SuggestedConfig",
    "TargetCandidate",
    "TargetProfile",
    "TaskInference",
    "TimeCandidate",
    "TransformAction",
    "ValueProfile",
    "VisualRecommendation",
    "add_date_features",
    "add_missing_indicators",
    "add_ratio",
    "apply_suggested_conversions",
    "branch",
    "clean_numeric_outliers",
    "clean_column_name",
    "clean_column_names",
    "connect_web",
    "is_save_mode",
    "all_lenses",
    "all_operation_specs",
    "get_lens_spec",
    "get_operation_spec",
    "help",
    "help_getdata",
    "help_tree",
    "impute_missing",
    "ledger_view",
    "leaf",
    "map_values",
    "modeling_catalog",
    "modeling_artifact",
    "modeling_experiment",
    "modeling_plan",
    "one_hot_encode",
    "optimize_footprint",
    "plot",
    "profile",
    "pull",
    "query",
    "rename_columns",
    "register_ipython_magics",
    "report",
    "scale_numeric",
    "scan",
    "scan_path",
    "suggest_visuals",
    "save",
    "save_mode",
    "files",
    "sources",
    "tree_view",
    "default_modeling_spec",
    "unify_binary_flags",
    "view",
    "visual_artifact",
    "visual_catalog",
    "visualize",
    "web",
    "web_payload",
    "workspace",
]

__version__ = "0.2.2"


def load_ipython_extension(ipython):
    """Register stateframe notebook magics such as ``%%sf_leaf``."""

    register_ipython_magics(ipython)
